### ISSUE TITLE
GET & DELETE subscription

### ISSUE THREAD

**Issue by gepdev** [ittweb/magento2-newsletter-api#1]
Hey! I've tried to use it in the storefront api... It works perfectly. It would be useful also to check if the user is subscribed or to delete the subscription to the newsletter.
Are you planning to add also GET and DELETE to the rest routes?

**Comment by rbianchi-ittweb** [comment]
Hey @gentip!
It's very likely that we will add this functionality in the future. Keep up to date with our releases by clicking on the buttons at the top star and watch.

Thank you!

**Comment by rbianchi-ittweb** [comment]
Hi @gepdev 
with this commit you're request is done:
https://github.com/ittweb/magento2-newsletter-api/commit/929f8749d5aa158133fd66e275af9e061a2b0325

Just to know: in the frontend of Vue Storefront, where is the possibility to unsubscribe to the newsletter?
